apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  selector:
    matchLabels:
      run: django-app
  replicas: 1
  template:
    metadata:
      labels:
        run: django-app
    spec:
      containers:
      - name: ip-service-app
        image: samya123/djangoapp:latest
        ports:
        - containerPort: 8080