apiVersion: v1
kind: Service
metadata:
  name: django-app
  labels:
    run: django-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007
    protocol: TCP
  selector:
    run: django-app